# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='question',
            name='question_title',
            field=models.CharField(default='Titel', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
