# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0004_auto_20161117_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='used_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.CharField(max_length=6),
        ),
    ]
