# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_auto_20161118_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='user',
        ),
        migrations.AddField(
            model_name='votes',
            name='question',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to='votes.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='votes',
            name='token',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='votes.Token'),
        ),
    ]
