# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0007_auto_20161118_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='votes',
            name='voting_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
